ENV = "shuttle"

# Anilist
ANILIST_CLIENT_ID = "<CLIENT_ID>"
ANILIST_SECRET = "<SECRET>"
REDIRECT_URL = "<REDIRECT_URL>"

# Sentry
SENTRY_DSN = "<SENTRY_DSN>"

# Rocket
SECRET = "<SECRET>"

# Database
DATABASE_URL = "<DB_URL_STRING>"
